url: ""
baseurl: "/"
permalink: /news/:title:output_ext

name: "Elsecar Main FC"
strapline: "Believe. Desire. Teamwork. Dedication."
about: "This Lottery Bingo game supports the fundraising efforts of our club, allowing us to provide excellent training sessions and engaging social events for our young players."
logo: "/assets/images/logo--emfc.png"

email: "secretary@elsecarmain.co.uk"
facebook: "https://www.facebook.com/groups/3158656954424539"
website: "https://www.elsecarmain.co.uk/"
address: "13 Armroyd Ln, Elsecar, Barnsley S74 8ES"
map-coords: "53.49459367844664, -1.424442542330539"
join: "https://forms.gle/GEkzAc9o6GSi95vf9"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from